### DISCUSSION TITLE
Push Notification on vebus L1 acpowersetpoint change

### DISCUSSION THREAD

**Discussion by Faqterson** [Danie10/gadgeteerza-homeassistant#8] [General]
Hi

I want to find out if you make use of Notifications to a mobile phone to monitor if there is a change in the Vebus.

```
- id: '1715706503318'
  alias: Geyser monitoring
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: 627a4d945d211e425ba355a62edf74cc
    entity_id: 6f300ff2da9f74b978882d95137a05a8
    domain: sensor
    below: -10
    above: 0
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition: []
  action:
  - service: notify.mobile_app_cph2565
    metadata: {}
    data:
      message: Geyser Stove Turned on
  mode: single

```

**Comment by Danie10** [comment]
@Faqterson no I'm sending voice notifications to the Google speakers in the house so everyone hears them. But the same automation will allow for adding notifications to one or more mobiles that have the HA app installed.

**Comment by Faqterson** [comment]
I need to get me google speaker as well, it sound amazing to have it announce a notification.
The code I provided didn't work at all. I didn't receive a notification this morning on the mobile app. 

I am now testing the SOC for notifications:
```
- id: '1715758911203'
  alias: SOC Notification
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.victron_battery_soc
    for:
      hours: 0
      minutes: 0
      seconds: 10
    above: 50
  - platform: numeric_state
    entity_id:
    - sensor.victron_battery_soc
    for:
      hours: 0
      minutes: 0
      seconds: 10
    above: 80
  - platform: numeric_state
    entity_id:
    - sensor.victron_battery_soc
    for:
      hours: 0
      minutes: 0
      seconds: 10
    above: 99
  condition: []
  action:
  - service: notify.mobile_app_cph2565
    metadata: {}
    data:
      message: SOC Above 50%
  mode: single 
```
